### ISSUE TITLE
Adding Data

### ISSUE THREAD

**Issue by karls4** [PioneerCode/pioneer-pagination#1]
Hi,

I am trying to pass data into my ViewBag, could you give me some ideas on how to do this?

I am using a model.

![image](https://cloud.githubusercontent.com/assets/22108543/21432976/ed4ed258-c865-11e6-9764-5198f7dac0a6.png)

**Comment by chad-ramos** [comment]
HI,

Are you asking how to put multiple paginated lists on a single page? 

Looks like you have made the proper calls to the service.  Based on your picture I am assuming that is a controller.  Meaning, in your View you should be able to pass those values you are holding as attributes like so.

```csharp
<pioneer-pagination info="@ViewBag.PaginatedMeta" route="/blog"></pioneer-pagination>
<pioneer-pagination info="@ViewBag.Full" route="/blog"></pioneer-pagination>
<pioneer-pagination info="@ViewBag.End" route="/blog"></pioneer-pagination>
<pioneer-pagination info="@ViewBag.Partial" route="/blog"></pioneer-pagination>
```

Let me know if it works.  If not, I can test it tomorrow and put a fix in for you. 

Best,

Chad

**Comment by karls4** [comment]
Sorry Chad,

I am asking how do I pass data into the page? I only want to have 1 list on the page with the data from Model.HouseBeamProjects.

**Comment by chad-ramos** [comment]
Still not 100% sure what you are asking.  Can you provide more details? 

### To get your model out to the client, in your controller...
```chsarp
return View(Model.HouseBeamProjects);
```

Chad

**Comment by chad-ramos** [comment]
@karls4 - Checking to see if ^ answered your question and if you have anything else you want to ask.

**Comment by chad-ramos** [comment]
Closed due to inactivity.
