### ISSUE TITLE
Exception with invalid selectedPageNumber

### ISSUE THREAD

**Issue by splite** [PioneerCode/pioneer-pagination#18]
When `selectedPageNumber` is invalid (like  somebody is tinkering with your url and insert page 0 or < 0*), pagination will throw exception.

Proposed solution:
I dont want to validate url input (becouse i would have to mimic 
the `PaginatedMetaService.GetLastPageInCollection()` method or at least make it public and... Well, thats not simple solution.) - but you can easilly clamp value to valid range like this:

```c#
public class PaginatedMetaService
{
...
  public PaginatedMetaModel GetMetaData(int collectionSize, int selectedPageNumber, int itemsPerPage)
  {
    selectedPageNumber = Math.Clamp(selectedPageNumber, 1, Math.Max(1,GetLastPageInCollection(collectionSize, itemsPerPage)));
    ...
  }
...
}
```  

*: or you have your own "page [0][1][2]" bug in your implementation of paging and you are all "well, frak it, lets see if there is any .net core paging component on github" and then, out of curiosity, you click on your own buggy page 0 button 😉

**Comment by chad-ramos** [comment]
@splite Currently reviewing. Will keep you updated with what I find.  Thanks.

**Comment by chad-ramos** [comment]
@splite Just confirmed this,  Working on a fix now. 

>ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

![image](https://user-images.githubusercontent.com/3170200/40514624-73b71c32-5f6f-11e8-80e2-1cbf365529b2.png)

**Comment by chad-ramos** [comment]
@splite Also, my understanding is there is no Math.Clamp function native to .NET.  What language are you coming from where you use that? I know it is part of ECMAScript 2017 but I rarely see it.

**Comment by splite** [comment]
Uh... I dont think i understand you - [System.Math](https://msdn.microsoft.com/en-us/library/system.math_methods(v=vs.110).aspx) is there from .NET 1.1 😄 

Also, i updated my issue after i send it, have to System.Math.Max() third parameter (to take care of overflow on other end of `1; GetLastPageInCollection()` range)

**Comment by splite** [comment]
Ah, i see - there is [an issue](https://github.com/dotnet/corefx/issues/467) on corefx to ADD Math.Clamp - looks like i have newer version then you...

Sorry, my bad.

Clamp is actually really easy method: `x = (x < a) ? a : ((x > b) ? b : x);`


```
public static int Clamp(int value, int min, int max)  
{  
    return (value < min) ? min : (value > max) ? max : value;  
}
```

**Comment by chad-ramos** [comment]
@splite Also worth mentioning the nuget feed has been bummed to 2.1.1, of which includes this issue.

**Comment by splite** [comment]
@chad-ramos I grabbed source code (to find whats wrong && to add more functionality to [PioneerPaginationTagHelper](https://github.com/PioneerCode/pioneer-pagination/blob/master/src/Pioneer.Pagination/PioneerPaginationTagHelper.cs) )

Like...

- Support for `asp-page="Page/Index"` + resolve Routing: no more generated html like `href="Page/Index?page=2"` when it should be `href="Page/2"`)
(Please note that asp-page is not MVC but Razor Pages*, should be easy to transfer to MVC routing. Have to add one more resolve to configuration.)

- asp-route-nameyourparam as in `<a asp-page="Page/Index" asp-route-p="2" asp-route-search="">2 </a>` to support paginated search

- To throw out `ViewBag` (its deprecated for RazorPages, there you use `ViewData` without strong types, becouse... reasons...) - in the end I did not need source for this, but hey... 🤣 

Can write you some features, if you want - but not as pull request, i am too lazy to write unit tests for routing 😉  😄 

*: i am comming from .net desktop apps, we are using mvvm or we are bust, Razor Pages with their mvp are much closer to my mind then mvc - too much "magic" (my method have name x, so i have to name view y), too much classes etc.
