### ISSUE TITLE
"Next page" button is always ahead by 2 pages

### ISSUE THREAD

**Issue by electricduck** [PioneerCode/pioneer-pagination#2]
![screen shot 2017-01-17 at 19 28 10](https://cloud.githubusercontent.com/assets/1594644/22036362/21f58eea-dceb-11e6-8263-c1ba316d32fc.png)

For example, here, "Next page" links to the 7th page, not the 2nd.

EDIT: Seems to always be two pages ahead of the last number displayed.

**Comment by chad-ramos** [comment]
@electricduck Was able to reproduce.  I will get a fix up soon.  Thanks! =)

**Comment by chad-ramos** [comment]
@electricduck - I just pushed a change to master that fixes the "next" and "previous" node indexing issues.   I also updated the appropriate NuGet package and it should be available to pull into your project once it finished indexing. 

[Direct link to Nuget package](https://www.nuget.org/packages/Pioneer.Pagination/1.1.0)

Let me know if you have any other issues....
