### ISSUE TITLE
Total Pages Calculation Error

### ISSUE THREAD

**Issue by stevenjamesfrank** [PioneerCode/pioneer-pagination#7]
I saw a similar issue that was fixed in 1.1.0 but I'm running 1.1.1 and it looks to be back (or something similar is happening).  

The totals page count calculation (at least) is inaccurate.  I have a collection of 53 total items, 10 items per page and the page count is showing as 5.  It looks like the remainder on the calculation is being dropped without adding the extra 1 to account for the leftover items.

![image](https://user-images.githubusercontent.com/31525193/30244872-3954422e-958d-11e7-99c1-5b54e7960d0d.png)

In the screenshot I'm using 9 per pages just to test things out but the behavior is the same.

**Comment by chad-ramos** [comment]
Thanks for filing the issue.  I will take a look on Monday and let you know what I find.

Best,

Chad

**Comment by chad-ramos** [comment]
@stevenjamesfrank So after thinking about this, I believe it is correct.  The Page collection is the meta data that is used to display the page numbers.  For example, based on your data, you would have pages that represent....

1, 2, 3, 4, 5

I total of 5 Page objects used to represent each node in the UI.

The Page collection is not synonyms with the totality of pages you are representing.

Unless of course, I am misunderstanding you. 😀 

Let me know,

Best,

Chad

**Comment by stevenjamesfrank** [comment]
Thanks for looking into this.  I probably should've included an example of behavior along with my supporting evidence.

I'll take you through my example and hopefully I can be a bit more clear for you.

Just to review, there are 53 total items in my example and I have the page size set to 10.

Here is the state of the control on the initial load of the page in question:
![image](https://user-images.githubusercontent.com/31525193/30380656-cf2c29c2-985f-11e7-92f4-80803a3b30a1.png)
There are only 5 pages displaying.  In other words, if I wanted to go directly to the last page, to see the last 3 records, I couldn't.

If I click "Next", this is what I get, still no way to get to the last page:
![image](https://user-images.githubusercontent.com/31525193/30380784-1f3ed41e-9860-11e7-90fa-639e0b76d320.png)

Click "Next" again, gives me this, still the same issue:
![image](https://user-images.githubusercontent.com/31525193/30380828-4255a9d2-9860-11e7-9c29-6e5ea6635b51.png)

Clicking "Next" again gets into some additional odd behavior:
![image](https://user-images.githubusercontent.com/31525193/30380871-612a6d16-9860-11e7-9813-ff4cd315cc7b.png)
Page 6 has now appeared but both the "Next" button and my direct link back to page 1 are now gone.

I hope this clarifies what I'm experiencing, my apologies for the incomplete initial post.  Of course, I could be doing something wrong in the code, let me know if you have any questions there.  The code seems pretty straight-forward, you've done a great job there.

Please advise.

**Comment by chad-ramos** [comment]
@stevenjamesfrank - I am still in the camp that it is behaving as expected. 

- If you have 53 total items, and you divide that by 10 while rounding up, you get a total of 6 pages. 
  - Which is why you are no longer seeing "Next" when you shift to a range that shows 2 through 6.
- The UI is modeled after Googles pagination.  Of which....
  - Has a floating range of 10 pages displayed at any given time.
     - I currently have a range of 5.
  - Has a buffer at the start and end of its collection
     - If you go to Google and do a search and start hitting next on the pagination...
        - You will notice that once you get to page 7, the range in which displays, shifts right. 

I am open to feature request if you have any.  For instance, I currently (nor does Google) don't support the ability to jump to the first or last page in the pagination list.  I like that idea and can allow for it through configuration. 

Let me know your thoughts, or if I am still missing something. 

Best,

Chad

**Comment by stevenjamesfrank** [comment]
Chad,

Thanks again for your attention to this.  I see your points and understand how your code works better now.

My one remaining question/issue is from the final screen snip;  why, when on page 4 of 6, has the "Next" button vanished?

Thanks again,
Steve

**Comment by chad-ramos** [comment]
@stevenjamesfrank 

Gotcha.  That is a bug for sure. Next should be displayed unless on the last page.

Thanks,

Chad

**Comment by chad-ramos** [comment]
@stevenjamesfrank 

Just published 1.1.2 with the proposed fix.  Let me know if you find anything else.

Thanks,

Chad

**Comment by stevenjamesfrank** [comment]
Just updated and tested, fantastic!  Thanks Chad.

**Comment by stevenjamesfrank** [comment]
Chad, 

If I have requests, do you want me to create a new Pull Request, or how would you like me to go about it?

Steve

**Comment by chad-ramos** [comment]
@stevenjamesfrank 

If you got a feature in mind, open an issue and let's discuss it first.  =)  

Best,

Chad
